const CITY_TIMEZONES = {
    "Lagos": "Africa/Lagos",
    "Abuja": "Africa/Lagos",
    "Cairo": "Africa/Cairo",
    "Nairobi": "Africa/Nairobi",
    "Johannesburg": "Africa/Johannesburg",
    "Accra": "Africa/Accra",
    "Algiers": "Africa/Algiers",
    "Casablanca": "Africa/Casablanca",
    "Addis Ababa": "Africa/Addis_Ababa",
    "Kinshasa": "Africa/Kinshasa",
    "New York": "America/New_York",
    "Los Angeles": "America/Los_Angeles",
    "Chicago": "America/Chicago",
    "Toronto": "America/Toronto",
    "Mexico City": "America/Mexico_City",
    "Sao Paulo": "America/Sao_Paulo",
    "Buenos Aires": "America/Argentina/Buenos_Aires",
    "Bogota": "America/Bogota",
    "Lima": "America/Lima",
    "Caracas": "America/Caracas",
    "Santiago": "America/Santiago",
    "Panama City": "America/Panama",
    "Quito": "America/Guayaquil",
    "Montevideo": "America/Montevideo",
    "Havana": "America/Havana",
    "London": "Europe/London",
    "Paris": "Europe/Paris",
    "Berlin": "Europe/Berlin",
    "Madrid": "Europe/Madrid",
    "Rome": "Europe/Rome",
    "Amsterdam": "Europe/Amsterdam",
    "Brussels": "Europe/Brussels",
    "Vienna": "Europe/Vienna",
    "Zurich": "Europe/Zurich",
    "Stockholm": "Europe/Stockholm",
    "Copenhagen": "Europe/Copenhagen",
    "Oslo": "Europe/Oslo",
    "Lisbon": "Europe/Lisbon",
    "Athens": "Europe/Athens",
    "Helsinki": "Europe/Helsinki",
    "Warsaw": "Europe/Warsaw",
    "Prague": "Europe/Prague",
    "Budapest": "Europe/Budapest",
    "Istanbul": "Europe/Istanbul",
    "Moscow": "Europe/Moscow",
    "Kyiv": "Europe/Kyiv",
    "Bucharest": "Europe/Bucharest",
    "Belgrade": "Europe/Belgrade",
    "Sofia": "Europe/Sofia",
    "Tokyo": "Asia/Tokyo",
    "Seoul": "Asia/Seoul",
    "Shanghai": "Asia/Shanghai",
    "Beijing": "Asia/Shanghai",
    "Singapore": "Asia/Singapore",
    "Bangkok": "Asia/Bangkok",
    "Jakarta": "Asia/Jakarta",
    "Manila": "Asia/Manila",
    "Kuala Lumpur": "Asia/Kuala_Lumpur",
    "Hong Kong": "Asia/Hong_Kong",
    "Taipei": "Asia/Taipei",
    "Hanoi": "Asia/Bangkok",
    "Colombo": "Asia/Colombo",
    "Karachi": "Asia/Karachi",
    "Mumbai": "Asia/Kolkata",
    "Delhi": "Asia/Kolkata",
    "Bangalore": "Asia/Kolkata",
    "Chennai": "Asia/Kolkata",
    "Kathmandu": "Asia/Kathmandu",
    "Dhaka": "Asia/Dhaka",
    "Islamabad": "Asia/Karachi",
    "Riyadh": "Asia/Riyadh",
    "Dubai": "Asia/Dubai",
    "Doha": "Asia/Qatar",
    "Kuwait City": "Asia/Kuwait",
    "Tehran": "Asia/Tehran",
    "Baghdad": "Asia/Baghdad",
    "Amman": "Asia/Amman",
    "Beirut": "Asia/Beirut",
    "Jerusalem": "Asia/Jerusalem",
    "Muscat": "Asia/Muscat",
    "Tbilisi": "Asia/Tbilisi",
    "Yerevan": "Asia/Yerevan",
    "Baku": "Asia/Baku",
    "Kabul": "Asia/Kabul",
    "Tashkent": "Asia/Tashkent",
    "Almaty": "Asia/Almaty",
    "Astana": "Asia/Almaty",
    "Vladivostok": "Asia/Vladivostok",
    "Novosibirsk": "Asia/Novosibirsk",
    "Ulaanbaatar": "Asia/Ulaanbaatar",
    "Sydney": "Australia/Sydney",
    "Melbourne": "Australia/Melbourne",
    "Perth": "Australia/Perth",
    "Adelaide": "Australia/Adelaide",
    "Brisbane": "Australia/Brisbane",
    "Canberra": "Australia/Sydney",
    "Auckland": "Pacific/Auckland",
    "Wellington": "Pacific/Auckland",
    "Suva": "Pacific/Fiji",
    "Port Moresby": "Pacific/Port_Moresby",
    "Honolulu": "Pacific/Honolulu",
    "Anchorage": "America/Anchorage",
    "Denver": "America/Denver",
    "Phoenix": "America/Phoenix",
    "Seattle": "America/Los_Angeles",
    "Boston": "America/New_York",
    "Philadelphia": "America/New_York",
    "San Francisco": "America/Los_Angeles",
    "Detroit": "America/Detroit",
    "Minneapolis": "America/Chicago",
    "Houston": "America/Chicago",
    "Dallas": "America/Chicago",
    "Atlanta": "America/New_York",
    "Miami": "America/New_York",
    "Tampa": "America/New_York",
    "Orlando": "America/New_York",
    "San Diego": "America/Los_Angeles",
    "Las Vegas": "America/Los_Angeles",
    "Montreal": "America/Toronto",
    "Calgary": "America/Edmonton",
    "Vancouver": "America/Vancouver",
    "Edmonton": "America/Edmonton",
    "Winnipeg": "America/Winnipeg",
    "Halifax": "America/Halifax",
    "Quebec City": "America/Toronto",
    "Ottawa": "America/Toronto",
    "Reykjavik": "Atlantic/Reykjavik",
    "Greenland": "America/Godthab",
    "Nuuk": "America/Godthab",
    "Anchorage": "America/Anchorage",
    "Fairbanks": "America/Anchorage",
    "Juneau": "America/Juneau",
    "Nome": "America/Nome",
    "Barrow": "America/Anchorage",
    "Pago Pago": "Pacific/Pago_Pago",
    "Apia": "Pacific/Apia",
    "Honiara": "Pacific/Guadalcanal",
    "Port Vila": "Pacific/Efate",
    "Nuku'alofa": "Pacific/Tongatapu",
    "Majuro": "Pacific/Majuro",
    "Funafuti": "Pacific/Funafuti",
    "Tarawa": "Pacific/Tarawa",
    "Palikir": "Pacific/Pohnpei",
    "Yaren": "Pacific/Nauru",
    "Ngerulmud": "Pacific/Palau",
    "Saipan": "Pacific/Saipan"
    // You can continue expanding this list as needed
  };
  